name: Remove Background CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest test/ -v
    
    - name: Build Docker image
      run: docker build -t rmbg .
    
    - name: Test Docker image
      run: |
        docker rm -f test-container || true
        
        docker run -d -p 5000:5000 --name test-container rmbg
        echo "Waiting for application to start..."
        timeout=60 # Maximum wait time in seconds
        interval=2 # Check every 2 seconds
        elapsed=0
        while ! curl -sf http://localhost:5000 > /dev/null; do
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for application to start."
            docker logs test-container
            docker stop test-container
            exit 1
          fi
          sleep $interval
          elapsed=$((elapsed + interval))
          echo "Still waiting..."
        done
        echo "Application started!"
        docker logs test-container # Keep logs for inspection
        docker exec test-container ls -la /app
        docker exec test-container ls -la /app/templates || echo "templates dir missing"
        echo "Running curl test..."
        curl -v http://localhost:5000 # Now run the actual test curl
        docker stop test-container


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Placeholder"